app/main/__init__.py
from flask import Blueprint

main_blueprint = Blueprint('main', __name__, template_folder='templates')

# activate the routing decorators
from . import views

app/main/views.py
from flask import render_template, request, current_app, flash
from . import main_blueprint
from ..project.models import Project
# This is the main entry, contain webpage with general purpose


@main_blueprint.route('/')
@main_blueprint.route('/home')
def home():
    """main entry
    
    :return: a simple animated homepage
    """
    
    return render_template('home.html')

@main_blueprint.route('/discover')
def discover():
    """Display projects in grid view, sorting results from the newest to the oldest
    
    :return: discover webpage
    """
    
    page = request.args.get('page', 1, type=int)
    projects = Project.query.order_by(Project.publish_time.desc()).paginate(page=page, per_page=current_app.config['POSTS_PER_PAGE'])  # projects / page

    return render_template('discover.html', projects=projects)

@main_blueprint.route('/search/', defaults={'query': ''}, methods=['POST', 'GET'])
@main_blueprint.route('/search/<string:query>', methods=['POST', 'GET'])
def search(query: str):
    """Simple search engine that search in Project ['team_name', 'project_description', 'project_name'] fields
    
    :param query: the keyword for search engine to perform search
    :return: search result display in discover webpage layout
    """
    
    print(f"Searching for: {query}")  # Debug
    page = request.args.get('page', 1, type=int)
    projects = Project.query.msearch(query).order_by(Project.publish_time.desc()).paginate(page=page, per_page=current_app.config['POSTS_PER_PAGE'])
    
    return render_template('discover.html', projects=projects, query=query)
    

@main_blueprint.route('/about')
def about():
    """A page for us to write about our motive, plans and credits
    
    :return: about.html
    """
    
    return render_template('about.html')

app/main/templates/about.html
{% extends "general layout.html" %}

{% block head %}
  <script src="https://unpkg.com/scroll-out/dist/scroll-out.min.js"></script>  <!-- Scroll out library! -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/general information.css') }}" />
{% endblock %}

{% block title %}关于我们{% endblock %}


{% block content %}
{% include 'general header.html' %}

<!-- Main Area ------------------------------------------------------------ -->
<div class="information-container">
    <div class="info-update">
        <h2>
            关于这个项目
        </h2>
        <p class="info-message">
            我们是交大20届的学生，写一些东西写一些东西写一些东西写一些东西写一些东西写一些东西写一些东西写一些东西写一些东西写一些东西
        </p>
        <p class="info-message">
            我觉得写这一个作品会对以后的学生会很有帮助，如果你对我们的作品感兴趣的话我们有把源代码<a href="https://github.com/LeeTeng2001/SJTU-ITE-Project-Platform">开源在Github</a>上。
        </p>
    </div>
    <div class="info-update">
        <h2>
            我们的组员？
        </h2>
        <p class="info-message">
            歇一歇东西上
        </p>
        <p class="info-message">
            xxxxxx
        </p>
    </div>
    <div class="info-update" id="credit">
        <h2>
            致谢
        </h2>
        <p class="info-message">
            感谢以下的资源让我们的项目得以实现：
        </p>
        <p class="info-message">
            pexel
        </p>
        <p class="info-message">
            unsplash
        </p>
        <p class="info-message">
            Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
        </p>
    </div>
</div>


{% include 'general footer.html' %}
{% endblock %}

app/main/templates/discover.html
{% extends "general layout.html" %}

{% block head %}
  <script src="https://unpkg.com/scroll-out/dist/scroll-out.min.js"></script>  <!-- Scroll out library! -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/discover.css') }}" />
{% endblock %}

{% block title %}工导项目展示{% endblock %}

{% block content %}
  {% include 'general header.html' %}
  <!-- Discover Headers ------------------------------------------------------------------------------ -->
  <div class="top-page">
    <img id="discover-background" src="{{ url_for('static', filename='resources/discover - background.jpg') }}" alt="background">
    <div class="top-page-shadow"></div>

    <div class="text-typewriter">
      <h1 class="text-title">开始·<b>启程</b></h1>
    </div>

    <div class="text-subtitle">
      <h3>下滑欣赏同学们的作品或提交你的作品</h3>
    </div>

    <div class="text-top-bottom">
      <h6 class="text-top-bottom-idx1"><a href="https://github.com/LeeTeng2001/SJTU-ITE-Project-Platform">上海交通学生</a>制作</h6>
      <h6 class="text-top-bottom-idx2">关于<a href="{{ url_for('main.about') }}">我们</a></h6>
      <h6 class="text-top-bottom-idx3">2021年工导课程项目作品</h6>
    </div>

    <!-- Pretty star effect -->
    <div class="star-container">
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
      <span class="shiny-star"></span>
    </div>
  </div>

  <!-- Gallery of photos -------------------------------------------------------------->
  <div class="box-layout-grid">
    <!-- BOX MAIN TEMPLATE -->
    {# REAL DATA ---------------------------------------------------------------------------------------- #}
    {% for project in projects.items %}
      <div class="box" data-scroll>
        <div class="box-img-main">
          <a href="{{ url_for('project.post', id=project.id) }}" >
            <img src="{{ url_for('static', filename='user resources/' + project.project_pic1) }}" alt="picture 1">
            <!-- TODO: Maybe add image overlay and scale effect -->
          </a>
          {% if current_user.is_authenticated %}
            {% if project in current_user.liked_projects  %}
              <i class="fas fa-heart heart-vector active" onclick="updateLike(this, {{ project.id }})"></i>
            {% else %}
              <i class="fas fa-heart heart-vector" onclick="updateLike(this, {{ project.id }})"></i>
            {% endif %}
          {% else %}
            <i class="fas fa-heart heart-vector" onclick="location.href='{{ url_for('user.login') }}'"></i>
          {% endif %}
        </div>
        <div class="box-body">
          <a href="{{ url_for('project.post', id=project.id) }}" class="box-title box-text-animation">{{ project.project_name }}</a>
          <div class="box-info-sub">
            <h5 class="box-teammates">{{ project.teammates }}</h5>
            <h5 class="box-date">{{ project.publish_time.strftime("%Y年%m月%d日") }}</h5>
          </div>
          <div class="box-info-main">
            <div>
              <img class="box-icon-img" src="{{ url_for('static', filename='resources/user avatars/' + project.publisher.user_avatar) }}" alt="profile pic">
              <a class="box-teamname box-text-animation" href="{{ url_for('project.post', id=project.id) }}">{{ project.publisher.username }}</a>
            </div>
            <div>
              <h5 class="box-total-likes">{{ project.get_liked_count() }}</h5>
              <img class="box-icon-img" src="{{ url_for('static', filename='resources/discover - heart.png') }}" alt="like icon">
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>


  <!-- divider and footer ------------------------------------------------------- -->
  <div class="pagination-line"></div>
  <!-- Footer navigation bar -->
  <div class="post-navigation">
    <ul>
      {% if projects.has_prev %}
        {% if query is defined %}
          <li><a href="{{ url_for('main.search', query=query, page=projects.page - 1) }}"><i class="fas fa-angle-left"></i> 上一页</a></li>
        {% else %}
          <li><a href="{{ url_for('main.discover', page=projects.page - 1) }}"><i class="fas fa-angle-left"></i> 上一页</a></li>
        {% endif %}
      {% else %}
      <li><a href="#" class="disabled"><i class="fas fa-angle-left"></i> 上一页</a></li>
      {% endif %}

      {% for page_num in projects.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if projects.page == page_num %}
            {% if query is defined %}
              <li><a href="{{ url_for('main.search', query=query, page=page_num) }}" class="active">{{ page_num }}</a></li>
            {% else %}
              <li><a href="{{ url_for('main.discover', page=page_num) }}" class="active">{{ page_num }}</a></li>
            {% endif %}
          {% else %}
            {% if query is defined %}
              <li><a href="{{ url_for('main.search', query=query, page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
              <li><a href="{{ url_for('main.discover', page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
          {% endif %}

        {% else %}
        <li><a href="#">...</a></li>
        {% endif %}
      {% endfor %}

      {% if projects.has_next %}
        {% if query is defined %}
          <li><a href="{{ url_for('main.search', query=query, page=projects.page + 1) }}">下一页 <i class="fas fa-angle-right"></i></a></li>
        {% else %}
          <li><a href="{{ url_for('main.discover', page=projects.page + 1) }}">下一页 <i class="fas fa-angle-right"></i></a></li>
        {% endif %}
      {% else %}
      <li><a href="#" class="disabled">下一页 <i class="fas fa-angle-right"></i></a></li>
      {% endif %}
    </ul>
  </div>

{% include 'general footer.html' %}

  <script>
    ScrollOut();


    // Ajax call ------------------------------------------------------------------------------------
    function updateLike(event, project_id) {
      // Ajax call
      fetch(`{{ url_for('project.toggle_like') }}/${project_id}`).then(function (response) {
        return response.text();
      }).then(function (text){
        console.log(text);
        // TODO: Do something here
      })

      // Instant feedback
      const likeCount = event.parentNode.parentNode.querySelector('.box-total-likes');
      const likeBtn = event;

      if (likeBtn.classList.contains('active')) {
        likeCount.innerHTML--;
      }
      else {
        likeCount.innerHTML++;
      }

      likeBtn.classList.toggle('active');
      // TODO: Add flush message here
    }

    // Parallax effect for background -------------------------------------------------------------------------------
    document.addEventListener("mousemove", parallex);
    function parallex(e) {
      const obj = this.querySelector("#discover-background");
      const speed = 3;  // Maybe randomize speed ?
      const x = (window.innerWidth - e.pageX * speed) / 100;
      const y = (window.innerHeight - e.pageY * speed) / 100;

      obj.style.transform = `scale(1.1) translateX(${x}px) translateY(${y}px)`
    }
  </script>
{% endblock %}

app/main/templates/home.html
{% extends "general layout.html" %}

{% block head %}
  <style>
    :root {
      --main-background-url: url('{{ url_for('static', filename='resources/main - background.jpg', _external=True) }}');
    }
  </style>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
{% endblock %}

{% block title %}
  欢迎工导项目展示
{% endblock %}

{% block content %}
  <div class="main-layout">
    <div class="navbar">
      <img src="{{ url_for('static', filename='resources/main - SJTU logo.png') }}" alt="LOGO" class="main-logo">
      <a href="{{ url_for('project.my_project') }}" class="btn-border gen-hover">提交作品</a>
    </div>

    <div class="content">
      <small>工导作品集合</small>
      <h1>见识<br>无穷无尽的灵感</h1>
      <a href="{{ url_for('main.discover') }}" class="btn-border gen-hover">我想看作品</a>
    </div>

    <div class="side-bar">
      <img src="{{ url_for('static', filename='resources/main - menu.png') }}" alt="menu" class="menu-btn">

      <div class="social-links">
          <img src="{{ url_for('static', filename='resources/main - fb.png') }}" alt="facebook">
          <img src="{{ url_for('static', filename='resources/main - ig.png') }}" alt="instagram">
          <img src="{{ url_for('static', filename='resources/main - tw.png') }}" alt="twitter">
      </div>
      <div class="other-links">
        <img src="{{ url_for('static', filename='resources/main - info.png') }}" alt="info">
        <img src="{{ url_for('static', filename='resources/main - share.png') }}" alt="share">
    </div>
    </div>

    <div class="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
      <img src="{{ url_for('static', filename='resources/main - bubble.png') }}" alt="bubbles">
    </div>
  </div>
{% endblock %}